"""adiciona novas tabelas

Revision ID: e407330d4889
Revises: 
Create Date: 2025-11-13 19:27:04.082121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e407330d4889'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinhos',
    sa.Column('id_carrinho', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('ATIVO', 'FINALIZADO', 'CANCELADO', 'EXPIRADO', name='status_carrinho_enum'), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='check_carrinho_subtotal_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carrinho')
    )
    op.create_index('idx_carrinho_ativo_expirado', 'carrinhos', ['status', 'expira_em'], unique=False)
    op.create_index('idx_carrinho_usuario_status', 'carrinhos', ['usuario_id', 'status'], unique=False)
    op.create_index(op.f('ix_carrinhos_expira_em'), 'carrinhos', ['expira_em'], unique=False)
    op.create_index(op.f('ix_carrinhos_status'), 'carrinhos', ['status'], unique=False)
    op.create_index(op.f('ix_carrinhos_usuario_id'), 'carrinhos', ['usuario_id'], unique=False)
    op.create_table('reservas',
    sa.Column('id_reserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='check_reserva_quantidade_positiva'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.codigo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_index('idx_reserva_ativa_expira', 'reservas', ['ativa', 'expira_em'], unique=False)
    op.create_index('idx_reserva_usuario_ativa', 'reservas', ['usuario_id', 'ativa'], unique=False)
    op.create_index(op.f('ix_reservas_ativa'), 'reservas', ['ativa'], unique=False)
    op.create_index(op.f('ix_reservas_expira_em'), 'reservas', ['expira_em'], unique=False)
    op.create_index(op.f('ix_reservas_produto_id'), 'reservas', ['produto_id'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    op.create_table('itens_carrinho',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('preco_unitario > 0', name='check_item_preco_positivo'),
    sa.CheckConstraint('quantidade > 0', name='check_item_quantidade_positiva'),
    sa.CheckConstraint('subtotal >= 0', name='check_item_subtotal_positivo'),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id_carrinho'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.codigo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_item'),
    sa.UniqueConstraint('carrinho_id', 'produto_id', name='uq_carrinho_produto')
    )
    op.create_index('idx_item_carrinho', 'itens_carrinho', ['carrinho_id'], unique=False)
    op.create_index(op.f('ix_itens_carrinho_carrinho_id'), 'itens_carrinho', ['carrinho_id'], unique=False)
    op.create_index(op.f('ix_itens_carrinho_produto_id'), 'itens_carrinho', ['produto_id'], unique=False)
    op.add_column('produtos', sa.Column('quantidade_reservada', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'quantidade_reservada')
    op.drop_index(op.f('ix_itens_carrinho_produto_id'), table_name='itens_carrinho')
    op.drop_index(op.f('ix_itens_carrinho_carrinho_id'), table_name='itens_carrinho')
    op.drop_index('idx_item_carrinho', table_name='itens_carrinho')
    op.drop_table('itens_carrinho')
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_produto_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_expira_em'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_ativa'), table_name='reservas')
    op.drop_index('idx_reserva_usuario_ativa', table_name='reservas')
    op.drop_index('idx_reserva_ativa_expira', table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_carrinhos_usuario_id'), table_name='carrinhos')
    op.drop_index(op.f('ix_carrinhos_status'), table_name='carrinhos')
    op.drop_index(op.f('ix_carrinhos_expira_em'), table_name='carrinhos')
    op.drop_index('idx_carrinho_usuario_status', table_name='carrinhos')
    op.drop_index('idx_carrinho_ativo_expirado', table_name='carrinhos')
    op.drop_table('carrinhos')
    # ### end Alembic commands ###
