"""estrutura inicial

Revision ID: fb23fd08740a
Revises: 
Create Date: 2025-11-18 17:16:51.865661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb23fd08740a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('dt_nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.CheckConstraint('LENGTH(cpf) = 11', name='check_cpf_length'),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index('idx_cliente_ativo', 'clientes', ['ativo'], unique=False)
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=True)
    op.create_table('produtos',
    sa.Column('codigo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vlr_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False, default=0),
    sa.Column('quantidade_reservada', sa.Integer(), nullable=False, default=0),
    sa.Column('margem_lucro', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('dt_cadastro', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantidade_estoque >= 0', name='check_estoque_nao_negativo'),
    sa.CheckConstraint('quantidade_reservada <= quantidade_estoque', name='check_reserva_menor_estoque'),
    sa.CheckConstraint('quantidade_reservada >= 0', name='check_reservada_nao_negativo'),
    sa.CheckConstraint('valor > 0', name='check_valor_positivo'),
    sa.CheckConstraint('valor >= vlr_compra', name='check_valor_maior_custo'),
    sa.CheckConstraint('vlr_compra > 0', name='check_vlr_compra_positivo'),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('nome', 'modelo', 'categoria', name='uq_produto')
    )
    op.create_index('idx_produto_ativo_categoria', 'produtos', ['ativo', 'categoria'], unique=False)
    op.create_index('idx_produto_estoque_baixo', 'produtos', ['quantidade_estoque', 'ativo'], unique=False)
    op.create_index(op.f('ix_produtos_ativo'), 'produtos', ['ativo'], unique=False)
    op.create_index(op.f('ix_produtos_categoria'), 'produtos', ['categoria'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=True),
    sa.Column('tipo_usuario', postgresql.ENUM('admin', 'gerente', 'vendedor', 'cliente', name='tipo_usuario_enum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index('idx_usuario_ativo_tipo', 'usuarios', ['ativo', 'tipo_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_ativo'), 'usuarios', ['ativo'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_tipo_usuario'), 'usuarios', ['tipo_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('carrinhos',
    sa.Column('id_carrinho', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('ATIVO', 'FINALIZADO', 'CANCELADO', 'EXPIRADO', name='status_carrinho_enum'), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='check_carrinho_subtotal_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carrinho')
    )
    op.create_index('idx_carrinho_ativo_expirado', 'carrinhos', ['status', 'expira_em'], unique=False)
    op.create_index('idx_carrinho_usuario_status', 'carrinhos', ['usuario_id', 'status'], unique=False)
    op.create_index(op.f('ix_carrinhos_expira_em'), 'carrinhos', ['expira_em'], unique=False)
    op.create_index(op.f('ix_carrinhos_status'), 'carrinhos', ['status'], unique=False)
    op.create_index(op.f('ix_carrinhos_usuario_id'), 'carrinhos', ['usuario_id'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', postgresql.ENUM('LOGIN', 'LOGOUT', 'CRIAR', 'ATUALIZAR', 'DELETAR', 'DESATIVAR', 'ATIVAR', 'AJUSTE_ESTOQUE', name='acao_enum'), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_anteriores', sa.Text(), nullable=True),
    sa.Column('dados_novos', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index('idx_log_acao', 'log_auditoria', ['acao', 'data_hora'], unique=False)
    op.create_index('idx_log_tabela', 'log_auditoria', ['tabela', 'registro_id'], unique=False)
    op.create_index('idx_log_usuario', 'log_auditoria', ['usuario_id', 'data_hora'], unique=False)
    op.create_index(op.f('ix_log_auditoria_acao'), 'log_auditoria', ['acao'], unique=False)
    op.create_index(op.f('ix_log_auditoria_data_hora'), 'log_auditoria', ['data_hora'], unique=False)
    op.create_table('reservas',
    sa.Column('id_reserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='check_reserva_quantidade_positiva'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.codigo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_index('idx_reserva_ativa_expira', 'reservas', ['ativa', 'expira_em'], unique=False)
    op.create_index('idx_reserva_usuario_ativa', 'reservas', ['usuario_id', 'ativa'], unique=False)
    op.create_index(op.f('ix_reservas_ativa'), 'reservas', ['ativa'], unique=False)
    op.create_index(op.f('ix_reservas_expira_em'), 'reservas', ['expira_em'], unique=False)
    op.create_index(op.f('ix_reservas_produto_id'), 'reservas', ['produto_id'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    op.create_table('vendas',
    sa.Column('id_venda', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', postgresql.ENUM('Dinheiro', 'Debito', 'Credito', 'PIX', name='forma_pagamento_enum'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_nome', sa.String(length=50), nullable=True),
    sa.CheckConstraint('desconto <= subtotal', name='check_desconto_menor_subtotal'),
    sa.CheckConstraint('desconto >= 0', name='check_desconto_positivo'),
    sa.CheckConstraint('subtotal >= 0', name='check_subtotal_positivo'),
    sa.CheckConstraint('total >= 0', name='check_total_positivo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id_cliente'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_venda')
    )
    op.create_index('idx_venda_cliente', 'vendas', ['cliente_id', 'data_hora'], unique=False)
    op.create_index('idx_venda_data', 'vendas', ['data_hora'], unique=False)
    op.create_index('idx_venda_vendedor', 'vendas', ['vendedor_id', 'data_hora'], unique=False)
    op.create_index(op.f('ix_vendas_data_hora'), 'vendas', ['data_hora'], unique=False)
    op.create_index(op.f('ix_vendas_vendedor_id'), 'vendas', ['vendedor_id'], unique=False)
    op.create_table('itens_carrinho',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrinho_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('preco_unitario > 0', name='check_item_preco_positivo'),
    sa.CheckConstraint('quantidade > 0', name='check_item_quantidade_positiva'),
    sa.CheckConstraint('subtotal >= 0', name='check_item_subtotal_positivo'),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id_carrinho'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.codigo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_item'),
    sa.UniqueConstraint('carrinho_id', 'produto_id', name='uq_carrinho_produto')
    )
    op.create_index('idx_item_carrinho', 'itens_carrinho', ['carrinho_id'], unique=False)
    op.create_index(op.f('ix_itens_carrinho_carrinho_id'), 'itens_carrinho', ['carrinho_id'], unique=False)
    op.create_index(op.f('ix_itens_carrinho_produto_id'), 'itens_carrinho', ['produto_id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venda', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('nome_produto', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('preco_unitario > 0', name='check_preco_positivo'),
    sa.CheckConstraint('quantidade > 0', name='check_quantidade_positiva'),
    sa.CheckConstraint('subtotal >= 0', name='check_subtotal_item_positivo'),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id_venda'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.codigo'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_index('idx_item_produto', 'itens_venda', ['produto_id'], unique=False)
    op.create_index('idx_item_venda', 'itens_venda', ['id_venda'], unique=False)
    op.create_index(op.f('ix_itens_venda_id_venda'), 'itens_venda', ['id_venda'], unique=False)
    op.create_table('movimentacoes_estoque',
    sa.Column('id_movimentacao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('ENTRADA', 'SAIDA', 'AJUSTE', 'RESERVA', 'LIBERACAO', name='tipo_movimentacao_enum'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('estoque_anterior', sa.Integer(), nullable=False),
    sa.Column('estoque_posterior', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('estoque_anterior >= 0', name='check_estoque_anterior_valido'),
    sa.CheckConstraint('estoque_posterior >= 0', name='check_estoque_posterior_valido'),
    sa.CheckConstraint('quantidade != 0', name='check_quantidade_nao_zero'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.codigo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id_venda'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_movimentacao')
    )
    op.create_index('idx_movimentacao_produto_data', 'movimentacoes_estoque', ['produto_id', 'data_hora'], unique=False)
    op.create_index('idx_movimentacao_tipo', 'movimentacoes_estoque', ['tipo', 'data_hora'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_data_hora'), 'movimentacoes_estoque', ['data_hora'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_produto_id'), 'movimentacoes_estoque', ['produto_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_estoque_tipo'), 'movimentacoes_estoque', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_estoque_tipo'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_produto_id'), table_name='movimentacoes_estoque')
    op.drop_index(op.f('ix_movimentacoes_estoque_data_hora'), table_name='movimentacoes_estoque')
    op.drop_index('idx_movimentacao_tipo', table_name='movimentacoes_estoque')
    op.drop_index('idx_movimentacao_produto_data', table_name='movimentacoes_estoque')
    op.drop_table('movimentacoes_estoque')
    op.drop_index(op.f('ix_itens_venda_id_venda'), table_name='itens_venda')
    op.drop_index('idx_item_venda', table_name='itens_venda')
    op.drop_index('idx_item_produto', table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_itens_carrinho_produto_id'), table_name='itens_carrinho')
    op.drop_index(op.f('ix_itens_carrinho_carrinho_id'), table_name='itens_carrinho')
    op.drop_index('idx_item_carrinho', table_name='itens_carrinho')
    op.drop_table('itens_carrinho')
    op.drop_index(op.f('ix_vendas_vendedor_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_data_hora'), table_name='vendas')
    op.drop_index('idx_venda_vendedor', table_name='vendas')
    op.drop_index('idx_venda_data', table_name='vendas')
    op.drop_index('idx_venda_cliente', table_name='vendas')
    op.drop_table('vendas')
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_produto_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_expira_em'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_ativa'), table_name='reservas')
    op.drop_index('idx_reserva_usuario_ativa', table_name='reservas')
    op.drop_index('idx_reserva_ativa_expira', table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_log_auditoria_data_hora'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_acao'), table_name='log_auditoria')
    op.drop_index('idx_log_usuario', table_name='log_auditoria')
    op.drop_index('idx_log_tabela', table_name='log_auditoria')
    op.drop_index('idx_log_acao', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_carrinhos_usuario_id'), table_name='carrinhos')
    op.drop_index(op.f('ix_carrinhos_status'), table_name='carrinhos')
    op.drop_index(op.f('ix_carrinhos_expira_em'), table_name='carrinhos')
    op.drop_index('idx_carrinho_usuario_status', table_name='carrinhos')
    op.drop_index('idx_carrinho_ativo_expirado', table_name='carrinhos')
    op.drop_table('carrinhos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_tipo_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_ativo'), table_name='usuarios')
    op.drop_index('idx_usuario_ativo_tipo', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_ativo'), table_name='produtos')
    op.drop_index('idx_produto_estoque_baixo', table_name='produtos')
    op.drop_index('idx_produto_ativo_categoria', table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.drop_index('idx_cliente_ativo', table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
